DROP DATABASE IF EXISTS `tchat`;

CREATE DATABASE `tchat`;

use `tchat`;

CREATE TABLE `users` (id INT AUTO_INCREMENT PRIMARY KEY, login VARCHAR(512), mdp VARCHAR(512));

CREATE TABLE `comments` (id INT AUTO_INCREMENT PRIMARY KEY, comment VARCHAR(2555),
 user INT, FOREIGN KEY `comments`(user) REFERENCES `users`(id));


